#!/bin/sh

# Check for merge conflicts

# Tested on Linux and Mac

# Simple check for merge conflics
conflicts=`git diff --cached --name-only -G"<<<<<|=====|>>>>>"`


# Something went wrong
if [[ -n "$conflicts" ]]; then
    echo
    echo "未解決のコンフリクトを解消してください:"

    for conflict in $conflicts; do
        echo $conflict
    done;

    exit 1;
fi

exit 0
